<?php
    $shop = new \Zend\Session\Container('shop');
    $info = $this->PaymentInfo()->getPaymentByShopId($shop['id']);
	
    if($info['uninstall'] == 1){
		header("Location: {$this->serverUrl($this->url('logout'))}");
	}
?>
<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
			->prependStylesheet($this->basePath('css/style.css'))
			->prependStylesheet($this->basePath('css/bootstrap-select.min.css'))
			->prependStylesheet($this->basePath('css/font-awesome.min.css'))
			->prependStylesheet('https://fonts.googleapis.com/css?family=PT+Sans:400,700')
			//->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
			->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
			->prependFile($this->basePath('js/bootstrap-select.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <?php 
                            if(isset($shop['id'])) {
                                if($info['trial_time']) {
                                    $left_seconds_trial = $info['trial_time'] - time();
                                    $left_days_trial =  $left_seconds_trial/60/60/24;
                                    if(ceil($left_days_trial) >= 1) { ?>
                                        <li>
                                            <a class="trial-counter" href="<?php echo $this->url('payment') ?>">Left <strong><?php echo ceil($left_days_trial); ?> days</strong> trial! Please get subscription.</a>
                                        </li>
                                    <?php } else { ?>
                                        <li>
                                            <a class="trial-counter-false" href="<?php echo $this->url('payment') ?>">Trial period is expired! <strong>Please get subscription.</strong></a>
                                        </li>
                                        <?php } ?>
    
                                <?php } elseif($info['trial_time'] == false) {
                                        $left_seconds_subscription = $info['payment_day'] - time();
                                        $left_days_subscription =  $left_seconds_subscription/60/60/24;
                                            if(ceil($left_days_subscription) <= 5 && ceil($left_days_subscription) > 0) { ?>
                                                <li>
                                                    <a class="trial-counter" href="<?php echo $this->url('payment') ?>">Left <strong><?php echo ceil($left_days_subscription); ?> days</strong> subscription!</a>
                                                </li>
                                            <?php } elseif (ceil($left_days_subscription) <= 0) { ?>
                                                <li>
                                                    <a class="trial-counter-false" href="<?php echo $this->url('payment') ?>">Your subscription is expired! <strong>Please get subscription.</strong></a>
                                                </li>
                                            <?php } ?>    
                                        <?php } ?>
                                <?php } ?>
                        <li>
                            <a href="<?php echo $this->url('get-started') ?>"><?php echo $this->translate('Get Started') ?></a>
                        </li>
                        <?php if(isset($shop['id'])) { ?>
                        <li>
                            <a href="<?php echo $this->url('logout') ?>"><span class="btn btn-success"><i class="fa fa-sign-out"></i>Logout</span></a>
                        </li>	
                        <?php } else { ?>
                        <li>
                            <a href="<?php echo $this->url('login') ?>"><span class="btn btn-success"><i class="fa fa-sign-in"></i>Login</span></a>
                        </li>
                        <?php } ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <footer>
            <div class="footer">
                <p>&copy; <?php echo date('Y'); ?> Quick-Product-Discount. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>